//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace DistinctDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerId { get; set; }
        [Required(ErrorMessage = "Please Enter FirstName")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please Enter LastName")]
        public string LastName { get; set; }

        public Nullable<int> TeamBelonged { get; set; }
        [Required(ErrorMessage = "Please enter the age")]
        [Range(18, 100, ErrorMessage = "Enter age between 18 to 100")]
        public Nullable<int> Age { get; set; }
        [Required(ErrorMessage = "Please enter the weight")]
        [Range(100, 500, ErrorMessage = "Enter age between 100 to 500")]
        public Nullable<int> Weight { get; set; }
        [Required(ErrorMessage = "Please enter the height")]
        public string Height { get; set; }
        public Nullable<int> JerseyNumber { get; set; }
        public virtual Team Team { get; set; }
    }
}
